export interface CardData {
    id: number;
    faction: string;
    type: string;
    name: string;
    power: number;
    ability: string;
    lore: string;
}

export const cardPool: CardData[] = [
    // Weather Cards
    { id: 1, type: "Weather", faction: "Effect", name: "Ionic Storm", power: 0, ability: "Weaken Close", lore: "Generated by high-altitude weather machines, Ionic Storms release charged particles that disrupt close-range combat equipment and personnel." },
    { id: 2, type: "Weather", faction: "Effect", name: "Gravitational Fog", power: 0, ability: "Weaken Range", lore: "Emitted from orbital platforms, Gravitational Fog warps local gravity, significantly hindering the operation of ranged weaponry." },
    { id: 3, type: "Weather", faction: "Effect", name: "Nano-Swarm Rain", power: 0, ability: "Weaken Siege", lore: "Nano-Swarm Rain consists of billions of microscopic robots that swarm siege equipment, jamming mechanics and electronics temporarily." },
    { id: 4, type: "Weather", faction: "Effect", name: "Atmospheric Equalizer", power: 0, ability: "Normalize", lore: "The Atmospheric Equalizer stabilizes weather conditions with a burst of neutralizing energy, restoring order to the battlefield environment." },
    // Human Close Combat Cards
    { id: 101, type: "Close Combat", faction: "Humanity", name: "Infantry Drone", power: 5, ability: "Tight Bond", lore: "Infantry Drones, modeled after ancient warriors but enhanced with lethal precision and unyielding stamina, lead the charge in ground battles across the cosmos." },
    { id: 102, type: "Close Combat", faction: "Humanity", name: "Cyber Knight", power: 7, ability: "Morale Boost", lore: "Cyber Knights are elite warriors, blending centuries-old combat traditions with modern exoskeleton enhancements." },
    { id: 103, type: "Close Combat", faction: "Humanity", name: "Mechanized Infantry", power: 6, ability: "Medic", lore: "These advanced combat suits can be airdropped into the fiercest fights, where their pilots provide crucial support and firepower." },
    { id: 104, type: "Close Combat", faction: "Humanity", name: "Exo-Soldier", power: 8, ability: "Agile", lore: "Exo-Soldiers wear suits powered by miniaturized fusion reactors, making them formidable assets in any engagement zone." },
    { id: 105, type: "Close Combat", faction: "Humanity", name: "Captain Elise Durant", power: 10, ability: "Hero", lore: "Captain Durant, a legendary pilot known for her daring maneuvers in close-quarters space combat, has now brought her expertise to the ground forces." },
    // Human Ranged Combat Cards
    { id: 111, type: "Ranged Combat", faction: "Humanity", name: "Tactical Sniper", power: 7, ability: "Scorch", lore: "Equipped with adaptive camouflage and high-velocity railguns, Tactical Snipers can change the tide of war from kilometers away." },
    { id: 112, type: "Ranged Combat", faction: "Humanity", name: "Recon Drone", power: 4, ability: "Spy", lore: "Recon Drones silently gather critical battlefield intelligence, often turning invisible to enemy sensors." },
    { id: 113, type: "Ranged Combat", faction: "Humanity", name: "Artillery Specialist", power: 6, ability: "Muster", lore: "Artillery Specialists control the battlefield with precise long-range bombardments, decimating enemy fortifications from afar." },
    { id: 114, type: "Ranged Combat", faction: "Humanity", name: "Comms Officer", power: 5, ability: "Morale Boost", lore: "Comms Officers maintain the flow of vital information across the battlefield, boosting the morale and coordination of allied troops." },
    { id: 115, type: "Ranged Combat", faction: "Humanity", name: "Lieutenant Marcus Fenix", power: 9, ability: "Hero", lore: "Marcus Fenix, a master sharpshooter, once turned the tide of a siege with a single shot that saved a thousand lives." },
    // Human Siege Cards
    { id: 121, type: "Siege", faction: "Humanity", name: "Siege Mech", power: 8, ability: "Medic", lore: "Siege Mechs are the heavy hitters in sieges, capable of breaking through any fortification with their massive firepower." },
    { id: 122, type: "Siege", faction: "Humanity", name: "Drone Carrier", power: 7, ability: "Muster", lore: "Drone Carriers deploy swarms of combat drones, overwhelming opponents with sheer numbers." },
    { id: 123, type: "Siege", faction: "Humanity", name: "Engineer Unit", power: 5, ability: "Tight Bond", lore: "Engineer Units are essential for maintaining and upgrading battlefield tech in real-time, ensuring peak performance under fire." },
    { id: 124, type: "Siege", faction: "Humanity", name: "Orbital Strike", power: 9, ability: "Obliterate Force", lore: "Orbital Strikes are the ultimate deterrence, called down from space stations orbiting above the conflict zone, devastating enemy lines from above." },
    { id: 125, type: "Siege", faction: "Humanity", name: "Engineer Sophia Bell", power: 11, ability: "Hero", lore: "Sophia Bell, chief engineer of the star fleet's artillery division, designs weapons that can break through any fortification." },
    // Human Leader Cards
    { id: 131, type: "Leader", faction: "Humanity", name: "Admiral Elara Myles", power: 0, ability: "Call Reinforcements", lore: "Admiral Elara Myles commands the human fleet with an iron will and a sharp mind, turning the tides of war with her strategic genius." },
    { id: 132, type: "Leader", faction: "Humanity", name: "General Carter Blake", power: 0, ability: "Orbital Bombardment", lore: "General Carter Blake, a seasoned war hero, coordinates devastating orbital strikes, breaking enemy lines with precision." },
    // Alien Close Combat Cards
    { id: 201, type: "Close Combat", faction: "Aliens", name: "Xenowarrior", power: 6, ability: "Agile", lore: "Xenowarriors, hailing from the dense jungles of Xylon, use bio-enhanced exoskeletons to adapt rapidly to any combat situation." },
    { id: 202, type: "Close Combat", faction: "Aliens", name: "Mind Leech", power: 4, ability: "Spy", lore: "Mind Leeches from the psychic swamps of Mindara can infiltrate enemy ranks undetected, sapping intelligence and disrupting strategies." },
    { id: 203, type: "Close Combat", faction: "Aliens", name: "Star Beast", power: 7, ability: "Morale Boost", lore: "Star Beasts, born in the nebulae of the Outer Rim, inspire awe and fear, boosting the morale of all allied forces with their presence." },
    { id: 204, type: "Close Combat", faction: "Aliens", name: "Plasma Berserker", power: 8, ability: "Muster", lore: "Plasma Berserkers use volatile energy cores to enhance their physical prowess, making them terrifying opponents in close quarters." },
    { id: 205, type: "Close Combat", faction: "Aliens", name: "Zara'keth of the Void", power: 10, ability: "Hero", lore: "Zara'keth, born from the dark energy of a collapsed star, wields void energy to dismantle his foes in close combat." },
    // Alien Ranged Combat Cards
    { id: 211, type: "Ranged Combat", faction: "Aliens", name: "Void Sniper", power: 7, ability: "Scorch", lore: "Void Snipers can hit targets across different dimensions, their shots bending through spacetime to strike with deadly precision." },
    { id: 212, type: "Ranged Combat", faction: "Aliens", name: "Quantum Trickster", power: 5, ability: "Spy", lore: "Quantum Tricksters use advanced holography to deceive and misdirect, turning the tides of battle without a single shot." },
    { id: 213, type: "Ranged Combat", faction: "Aliens", name: "Orb Weaver", power: 6, ability: "Medic", lore: "Orb Weavers, from the crystal forests of Oraclon, create protective shields around allies, weaving fate and fortune." },
    { id: 214, type: "Ranged Combat", faction: "Aliens", name: "Galactic Ranger", power: 5, ability: "Agile", lore: "Galactic Rangers patrol the edge of known space, equipped with phase rifles and stealth tech, ready to engage threats before they reach civilized worlds." },
    { id: 215, type: "Ranged Combat", faction: "Aliens", name: "Glim Shadoow", power: 9, ability: "Hero", lore: "Glim Shadoow, an assassin from the silent moons of Galorix, never misses her target, her arrows guided by the winds of fate." },
    // Alien Siege Cards
    { id: 221, type: "Siege", faction: "Aliens", name: "Meteor Launcher", power: 9, ability: "Obliterate Force", lore: "Meteor Launchers harness the power of celestial bodies, directing small planetoids to devastating effect on the battlefield." },
    { id: 222, type: "Siege", faction: "Aliens", name: "Singularity Cannon", power: 8, ability: "Scorch", lore: "Singularity Cannons create black holes on demand, swallowing clusters of enemy troops in one fell swoop." },
    { id: 223, type: "Siege", faction: "Aliens", name: "Gravity Sling", power: 7, ability: "Muster", lore: "Gravity Slings alter the battlefield's gravity, pulling enemies into strategic traps or hurling large debris as deadly projectiles." },
    { id: 224, type: "Siege", faction: "Aliens", name: "Bio-Engineer", power: 6, ability: "Medic", lore: "Bio-Engineers can regenerate fallen allies and reanimate the local flora and fauna to serve as organic siege weapons." },
    { id: 225, type: "Siege", faction: "Aliens", name: "Thorrus the World Builder", power: 11, ability: "Hero", lore: "Thorrus, using ancient cosmic energies, constructs siege devices that can alter planetary landscapes at his whim." },
    // Alien Leader Cards
    { id: 231, type: "Leader", faction: "Aliens",name: "High Councillor Xel'Naga", power: 0, ability: "Mind Warp", lore: "Xel'Naga, the enigmatic leader of the Alien High Council, manipulates the battlefield with a mere thought, turning enemy strengths into weaknesses." },
    { id: 232, type: "Leader", faction: "Aliens",name: "Warlord Kra'gh the Merciless", power: 0, ability: "Frenzy Assault", lore: "Kra'gh the Merciless leads his warrior kin into battle with ferocity unmatched, inspiring fear and admiration." },
    // Android Close Combat Cards
    { id: 401, type: "Close Combat", faction: "Androids", name: "Assault Construct", power: 6, ability: "Tight Bond", lore: "Assault Constructs are frontline combat units designed for maximum damage in close quarters, built with titanium alloy frames and AI-driven combat protocols." },
    { id: 402, type: "Close Combat", faction: "Androids", name: "Guardian Automaton", power: 7, ability: "Morale Boost", lore: "Guardian Automatons serve as protective units, equipped with energy shields and crowd-control armaments to defend key assets." },
    { id: 403, type: "Close Combat", faction: "Androids", name: "Combat Engineer", power: 5, ability: "Medic", lore: "Combat Engineers are specialized androids capable of repairing or even upgrading fellow units under fire, ensuring operational effectiveness at all times." },
    { id: 404, type: "Close Combat", faction: "Androids", name: "Blade Runner", power: 8, ability: "Agile", lore: "Blade Runners are swift, lethal units designed for rapid assaults and quick eliminations, using mono-molecular blade technology." },
    { id: 415, type: "Close Combat", faction: "Androids", name: "A.X. Titanus", power: 10, ability: "Hero", lore: "A.X. Titanus, the ultimate combat android, built with adaptive nano-armor, excels in decimating enemy lines with unparalleled ferocity." },
    // Android Ranged Combat Cards
    { id: 405, type: "Ranged Combat", faction: "Androids", name: "Sniper Synth", power: 7, ability: "Scorch", lore: "Sniper Synths utilize advanced targeting systems and stealth technology to take out high-value targets from great distances." },
    { id: 406, type: "Ranged Combat", faction: "Androids", name: "Infiltrator Drone", power: 4, ability: "Spy", lore: "Infiltrator Drones are small, flying units equipped with surveillance tech, capable of gathering crucial intelligence while remaining undetected." },
    { id: 407, type: "Ranged Combat", faction: "Androids", name: "Artillery Node", power: 6, ability: "Muster", lore: "Artillery Nodes are stationary units that coordinate devastating long-range attacks, linking up with other nodes for enhanced firepower." },
    { id: 408, type: "Ranged Combat", faction: "Androids", name: "Hacker Mech", power: 5, ability: "Morale Boost", lore: "Hacker Mechs can disrupt enemy communications and take control of hostile tech, turning the tide of battle by sowing confusion." },
    { id: 416, type: "Ranged Combat", faction: "Androids", name: "Vera-6 Marksman", power: 9, ability: "Hero", lore: "Vera-6, designed for precision elimination, has optics that can target an enemy's weakness from over the horizon." },
    // Android Siege Cards
    { id: 409, type: "Siege", faction: "Androids", name: "Siege Platform", power: 9, ability: "Destroy a row", lore: "Siege Platforms are heavy-duty war machines, equipped with long-range missiles and autonomous targeting systems, designed to breach fortifications." },
    { id: 410, type: "Siege", faction: "Androids", name: "Orbital Deployer", power: 8, ability: "Scorch", lore: "Orbital Deployers orbit the planet and can launch precision strikes or deploy additional units directly into the heart of the battlefield." },
    { id: 411, type: "Siege", faction: "Androids", name: "Gravity Distorter", power: 7, ability: "Muster", lore: "Gravity Distorters manipulate the gravitational fields on the battlefield, disrupting enemy formations and creating opportunities for allied attacks." },
    { id: 412, type: "Siege", faction: "Androids", name: "Nano-Repair Unit", power: 6, ability: "Medic", lore: "Nano-Repair Units swarm damaged androids, using nanotechnology to quickly repair and reactivate them during combat." },
    { id: 417, type: "Siege", faction: "Androids", name: "Constructor Prime", power: 11, ability: "Hero", lore: "Constructor Prime builds siege machinery with intelligent automation, making each machine a fortress unto itself." },
    // Android Faction Leader Cards
    { id: 413, type: "Leader", faction: "Androids", name: "AI Overlord Vector", power: 0, ability: "System Override", lore: "Vector, the self-aware AI Overlord, commands the android legions with cold logic and tactical brilliance, often turning the enemy's tools against them." },
    { id: 414, type: "Leader", faction: "Androids", name: "Command Unit Alpha-5", power: 0, ability: "Tactical Redeployment", lore: "Alpha-5, a tactical genius among android commanders, excels in fluid battle strategies, constantly adapting to the changing tides of war." },
    // Rebel Close Combat Cards
    { id: 301, type: "Close Combat", faction: "Rebels", name: "Marauder Leader", power: 6, ability: "Tight Bond", lore: "Marauder Leaders are charismatic and fierce, able to rally scattered groups of rebels into cohesive fighting units." },
    { id: 302, type: "Close Combat", faction: "Rebels", name: "Hybrid Fighter", power: 7, ability: "Morale Boost", lore: "Hybrid Fighters, born from mixed species, bring unique abilities to the rebel ranks, boosting morale with their presence and prowess." },
    { id: 303, type: "Close Combat", faction: "Rebels", name: "Guerrilla Engineer", power: 5, ability: "Medic", lore: "Guerrilla Engineers excel in modifying and repairing equipment on the fly, keeping rebel tech functional under harsh conditions." },
    { id: 304, type: "Close Combat", faction: "Rebels", name: "Rogue Android", power: 8, ability: "Agile", lore: "Rogue Androids, having broken free from their programming, offer unmatched combat skills and versatility to the rebel cause." },
    { id: 315, type: "Close Combat", faction: "Rebels", name: "Kara the Freedom Fighter", power: 10, ability: "Hero", lore: "Kara, once a high-ranking military commander, now leads a band of rebels with unmatched grit and determination in close combat." },
    // Rebel Ranged Combat Cards
    { id: 305, type: "Ranged Combat", faction: "Rebels", name: "Sniper Outcast", power: 7, ability: "Scorch", lore: "Sniper Outcasts are loners by nature but invaluable for their uncanny ability to eliminate key targets from great distances." },
    { id: 306, type: "Ranged Combat", faction: "Rebels", name: "Rebel Saboteur", power: 4, ability: "Spy", lore: "Rebel Saboteurs infiltrate enemy lines to gather intelligence and create chaos, sowing discord before major assaults." },
    { id: 307, type: "Ranged Combat", faction: "Rebels", name: "Resistance Fighter", power: 6, ability: "Muster", lore: "Resistance Fighters are the backbone of the rebel force, ready to swarm the enemy with sheer numbers and relentless fervor." },
    { id: 308, type: "Ranged Combat", faction: "Rebels", name: "Hacker Collective", power: 5, ability: "Morale Boost", lore: "The Hacker Collective disrupts enemy communications and commandeers their technology, turning the tide of battle in favor of the rebels." },
    { id: 316, type: "Ranged Combat", faction: "Rebels", name: "Silas the Ghost", power: 9, ability: "Hero", lore: "Silas, known as 'The Ghost,' uses guerrilla tactics to strike from the shadows, his presence barely noticed until it's too late." },
    // Rebel Siege Cards
    { id: 309, type: "Siege", faction: "Rebels", name: "Artillery Scavenger", power: 9, ability: "Destroy a row", lore: "Artillery Scavengers repurpose old or abandoned weapons to create devastating makeshift artillery, surprising enemies with unexpected firepower." },
    { id: 310, type: "Siege", faction: "Rebels", name: "Tech Guerrilla", power: 8, ability: "Scorch", lore: "Tech Guerrillas use salvaged and hacked devices to launch precise and deadly attacks, often turning the enemy's own technology against them." },
    { id: 311, type: "Siege", faction: "Rebels", name: "Rebellion Engineer", power: 7, ability: "Muster", lore: "Rebellion Engineers are masters of improvisation, capable of quickly assembling powerful weapons and defenses from whatever is at hand." },
    { id: 312, type: "Siege", faction: "Rebels", name: "Mobile Command", power: 6, ability: "Medic", lore: "Mobile Commands are converted vehicles that serve as operational hubs on the move, coordinating rebel actions and reviving fallen comrades." },
    { id: 317, type: "Siege", faction: "Rebels", name: "Engineer Lexi Volt", power: 11, ability: "Hero", lore: "Lexi Volt, using scavenged tech, constructs powerful siege weapons that have turned the tide of many battles for the rebels." },
    // Rebel Leader Cards
    { id: 313, type: "Leader", faction: "Rebels", name: "Renegade Captain Lyra", power: 0, ability: "Guerrilla Tactics", lore: "Captain Lyra, once a high-ranking officer, now leads a faction of rebels with her cunning and guile, always staying one step ahead." },
    { id: 314, type: "Leader", faction: "Rebels", name: "The Outcast Prince, Jorin", power: 0, ability: "Last Stand", lore: "Prince Jorin, exiled from his homeworld, has become a symbol of hope and resistance, rallying disparate groups under his banner." },
];
